import {readFile,writeFile,mkdir} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const policy=JSON.parse(await readFile(new URL('app/assets/legal/privacy.json',root),'utf8'));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shell=(title,body)=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · TAP Work</title><style>body{margin:0;background:#101112;color:#f0f2f4;font:16px/1.75 system-ui,sans-serif}main{max-width:760px;margin:auto;padding:40px 24px}h1{font-size:28px}h2{font-size:20px;margin-top:32px}a{color:#46c69b}p,li{overflow-wrap:anywhere}nav{display:flex;gap:24px;flex-wrap:wrap}footer{margin-top:40px;color:#a0a7af}</style></head><body><main><nav><a href="/">TAP Work</a><a href="/privacy/">개인정보처리방침</a><a href="/delete-account/">계정 삭제</a></nav><h1>${escape(title)}</h1>${body}<footer>${escape(policy.operator)} · ${escape(policy.effectiveDate)} · <a href="mailto:${escape(policy.contact)}">${escape(policy.contact)}</a></footer></main></body></html>`;
const privacy=shell(policy.title,policy.sections.map(s=>`<section><h2>${escape(s.title)}</h2>${s.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}</section>`).join(''));
const deletion=shell('계정 및 데이터 삭제',`<p>${escape(policy.operator)}의 TAP Work 계정은 앱에서 직접 삭제할 수 있습니다.</p><ol><li>TAP Work에서 로그인합니다.</li><li>상단 계정 버튼 → 내 계정 → 삭제 범위 확인을 선택합니다.</li><li>표시된 범위를 확인하고 계정 영구 삭제를 선택합니다.</li></ol><p>유일한 사장님은 매장 전체 데이터와 크루의 해당 매장 접근도 함께 삭제합니다. 다른 크루의 로그인 계정은 삭제하지 않습니다. 공유 기록과 직접 저장한 파일의 처리 범위는 <a href="/privacy/">개인정보처리방침</a>을 확인해 주세요.</p><p>앱에 로그인할 수 없거나 앱 없이 삭제를 요청하려면 <a href="mailto:${escape(policy.contact)}?subject=TAP%20Work%20계정%20삭제%20요청">계정 삭제 요청 이메일 보내기</a>를 선택하세요. 로그인에 사용한 이메일과 요청 내용을 알려 주세요. 비밀번호·인증 코드·신분증은 첨부하지 마세요. 필요한 본인 확인 후 처리 결과를 회신합니다.</p><p>Apple 로그인 연결을 해제하며, Apple 구독을 이용 중이라면 구독은 Apple 설정에서 별도로 취소해야 합니다.</p>`);
for(const [name,html] of [['privacy',privacy],['delete-account',deletion]]){
  const directory=new URL(`app/web/${name}/`,root);await mkdir(directory,{recursive:true});await writeFile(new URL('index.html',directory),html);
}
console.log('Privacy and account-deletion pages generated from the bundled policy.');
