import test from 'node:test';
import assert from 'node:assert/strict';
import {OperationsStore,emptyOperations} from '../operations.mjs';
import {manualCatalog} from '../manual_market.mjs';
import {composeManual,saveManualSetup} from '../manual_setup.mjs';
import {savePlace} from '../place_guide.mjs';
const now=new Date('2026-10-09T04:00:00Z');
function fixture(){let state=emptyOperations(now,'owner','사장님');const store=new OperationsStore(null,()=>now,{actor:{id:'owner',name:'사장님',role:'owner'},persistence:{read:async()=>structuredClone(state),save:async x=>{state=structuredClone(x);}}});const act=async(action,input={})=>{const v=await store.snapshot();return store.mutate('owner',{action,revision:v.revision,...input});};return {store,act,raw:()=>state};}
test('places can be created without geometry; floor/photo and references survive legacy map saves',async()=>{const x=fixture();let v=await x.act('save_place',{place:{id:'upstairs',name:'비품 창고',kind:'storage',floor:'2층',area:'계단 옆',description:'왼쪽 선반',photo:''}});assert.equal(v.zones[0].mapped,false);v=await x.act('save_layout',{layout:v.layout,zones:[]});assert.equal(v.zones[0].floor,'2층');const rev=v.revision;await x.act('save_place',{place:{...v.zones[0],name:'비품실'}});await assert.rejects(x.store.mutate('owner',{action:'save_place',revision:rev,place:v.zones[0]}),{status:409});});
test('image protocols/size and unrecognized place references rejected atomically',()=>{const s=emptyOperations(now,'owner','사장님');assert.throws(()=>savePlace(s,{place:{id:'p',kind:'storage',name:'창고',photo:'javascript:alert(1)'}},now));assert.equal(s.zones.length,0);assert.throws(()=>saveManualSetup(s,{places:{waste:'missing'}}));assert.equal(s.store.manualSetup,undefined);});
test('conditional composition retains original customized steps and shares one location',()=>{const s=emptyOperations(now,'owner','사장님');savePlace(s,{place:{id:'w',kind:'storage',name:'배출 장소',floor:'외부',photo:''}},now);const t={id:'t',steps:[{id:'step-1',title:'셀프바',manual:'내 사진 설명'},{id:'custom',title:'앞치마 수거'}]};s.catalogLinks={t:{sourceId:'bonejjim/hall-close'}};saveManualSetup(s,{conditions:{selfbar:false},places:{waste:'w'}});assert.deepEqual(composeManual(s,t).steps.map(s=>s.id),['custom']);assert.equal(t.steps.length,2);assert.equal(composeManual(s,t).sharedPlaces[0].name,'배출 장소');saveManualSetup(s,{conditions:{selfbar:true},places:{waste:'w'}});assert.equal(composeManual(s,t).steps[0].manual,'내 사진 설명');assert.equal(t.manualCustomization,undefined);});
test('real manual edits mark customization; common place edits do not',async()=>{const x=fixture();let v=await x.act('import_market_taps',{sourceIds:['bonejjim/hall-close'],releaseId:manualCatalog.releaseId,operationId:'import-hall-test',folderMode:'purpose'});const t=v.taskTemplates[0];assert.equal(t.manualCustomization,undefined);v=await x.act('save_manual_tap',{templateId:t.id,title:t.title,emoji:t.emoji,folderId:t.folderId,steps:t.steps.map((s,i)=>({...s,manual:i===0?'우리 매장 정리 기준':s.manual}))});assert.equal(v.taskTemplates[0].manualCustomization.kind,'modified');assert.equal(v.manualSearch[0].manualCustomization.kind,'modified');await x.act('save_manual_setup',{setup:{conditions:{selfbar:false}}});assert.equal(x.raw().taskTemplates[0].steps.length,t.steps.length);assert.equal((await x.store.snapshot()).manualSearch.some(s=>s.sourceStepId==='step-1'),false);});
test('condition changes rebuild only unstarted occurrences with unique IDs and preserve started snapshots',async()=>{const x=fixture();let v=await x.act('import_market_taps',{sourceIds:['bonejjim/hall-close'],releaseId:manualCatalog.releaseId,operationId:'import-snapshot-123',folderMode:'purpose'});const t=v.taskTemplates[0];v=await x.act('save_tap_settings',{templateId:t.id,assignmentScopeVersion:2,settings:{...t.settings,usage:'routine',enabled:true,assignment:{mode:'anyone'}}});const first=v.tasks.find(t=>t.templateId===v.taskTemplates[0].id);assert.ok(first);v=await x.act('save_manual_setup',{setup:{conditions:{selfbar:false}}});const next=v.tasks.find(t=>t.templateId===first.templateId);assert.notEqual(next.id,first.id);assert.ok(!next.steps.some(s=>s.id==='step-1'));assert.equal(new Set(x.raw().tasks.map(t=>t.id)).size,x.raw().tasks.length);await x.act('complete_step',{taskId:next.id,stepId:next.steps[0].id});v=await x.act('save_manual_setup',{setup:{conditions:{selfbar:true}}});assert.equal(v.tasks.find(t=>t.id===next.id).steps.length,next.steps.length);assert.equal(x.raw().taskTemplates[0].steps.length,5);});
test('floor-scoped geometry edits preserve other floors and location metadata',async()=>{const x=fixture();let v=await x.act('save_layout',{layout:{name:'매장',columns:16,rows:12},floorScope:'1층',zones:[{id:'one',kind:'storage',name:'창고1',description:'',floor:'1층',x:1,y:1,width:2,height:2,seats:0}]});v=await x.act('save_layout',{layout:v.layout,floorScope:'2층',zones:[{id:'two',kind:'storage',name:'창고2',description:'',floor:'2층',x:1,y:1,width:2,height:2,seats:0}]});assert.equal(v.zones.length,2);assert.equal(v.zones.find(z=>z.id==='one').floor,'1층');await assert.rejects(x.act('save_layout',{layout:v.layout,floorScope:'2층',zones:[{...v.zones.find(z=>z.id==='one'),floor:'2층'}]}));});
test('shared manual place references prevent map deletion',async()=>{const x=fixture();let v=await x.act('save_layout',{layout:{name:'매장',columns:16,rows:12},zones:[{id:'waste',kind:'storage',name:'배출 장소',description:'',x:1,y:1,width:2,height:2,seats:0}]});await x.act('save_manual_setup',{setup:{places:{waste:'waste'}}});await assert.rejects(x.act('save_layout',{layout:v.layout,zones:[]}),{status:400});assert.equal(x.raw().zones[0].id,'waste');});
test('unrelated checklist saves retain existing customization badges',async()=>{const x=fixture();let v=await x.act('import_market_taps',{sourceIds:['bonejjim/hall-close'],releaseId:manualCatalog.releaseId,operationId:'import-custom-retention',folderMode:'purpose'});let t=v.taskTemplates[0];v=await x.act('save_manual_tap',{templateId:t.id,title:t.title,emoji:t.emoji,folderId:t.folderId,steps:t.steps.map((s,i)=>({...s,manual:i===0?'매장 고유 내용':s.manual}))});t=v.taskTemplates[0];assert.equal(t.manualCustomization.kind,'modified');v=await x.act('save_checklists',{folders:v.checklistFolders,templates:v.taskTemplates});assert.deepEqual(v.taskTemplates[0].manualCustomization,t.manualCustomization);});
