import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { OperationsStore } from '../operations.mjs';
async function setup(t) {
  const dir = await mkdtemp(path.join(tmpdir(), 'tap2work-workplace-'));
  t.after(() => rm(dir, { recursive:true, force:true }));
  const store = new OperationsStore(path.join(dir,'state.json'), () => new Date('2026-09-28T03:00:00Z'));
  const act = async (actor, action, values={}) => store.mutate(actor, {revision:(await store.snapshot(actor)).revision,action,...values});
  return {store,act};
}
test('parts preserve IDs, reject removal and stale drafts, and save staff selections', async t => {
  const {store,act}=await setup(t);
  const before=await store.snapshot('owner');
  const parts=before.workplace.parts;
  const next=await act('owner','save_workplace_parts',{parts:[...parts,{name:'포장'}]});
  assert.equal(next.workplace.parts.length,4);
  assert.equal(next.workplace.parts[0].id,parts[0].id);
  await assert.rejects(store.mutate('owner',{action:'save_workplace_parts',revision:before.revision,parts}),{status:409});
  await assert.rejects(act('owner','save_workplace_parts',{parts:parts.slice(1)}),{status:400});
  const saved=await act('owner','save_staff_profile',{tapperId:'tapper-crew',partIds:[next.workplace.parts[3].id],bands:['오픈']});
  assert.deepEqual(saved.tappers.find(t=>t.id==='tapper-crew').workProfile.bands,['오픈']);
  await assert.rejects(act('crew','save_staff_profile',{tapperId:'tapper-crew',partIds:[],bands:[]}),{status:403});
});
test('day bands validate boundaries and apply independently or to all days without changing assigned shifts', async t => {
  const {store,act}=await setup(t);
  const before=await store.snapshot('owner');
  const bands=[{name:'오픈',start:'09:00',end:'13:30'},{name:'마감',start:'13:30',end:'22:00'}];
  let next=await act('owner','save_workplace_day',{weekday:7,bands});
  assert.deepEqual(next.workplace.days['7'],bands);
  assert.equal(next.workplace.days['1'],undefined);
  next=await act('owner','save_workplace_day',{weekday:7,bands,allDays:true});
  assert.equal(Object.keys(next.workplace.days).length,7);
  assert.deepEqual(next.staffShifts,before.staffShifts);
  await assert.rejects(act('owner','save_workplace_day',{weekday:1,bands:[bands[0],{...bands[1],start:'12:30'}]}),{status:400});
  await assert.rejects(act('owner','save_workplace_day',{weekday:1,bands:[{name:'야간',start:'22:00',end:'06:00'}]}),{status:400});
});
test('role restrictions are enforced on the server and completion projection; pay stays owner-only', async t => {
  const {store,act}=await setup(t);
  await act('owner','save_workplace_permissions',{role:'crew',permissions:{complete:false,stock:false}});
  const crew=await store.snapshot('crew');
  assert.equal(crew.workplace.restrictions,undefined);
  assert.equal(crew.labor,undefined);
  assert.ok(crew.tasks.every(t=>!t.canComplete));
  const task=crew.tasks.find(t=>t.kind==='routine'&&t.requiredRole==='all');
  await assert.rejects(act('crew','complete_task',{taskId:task.id}),{status:403});
  await assert.rejects(act('crew','save_workplace_permissions',{role:'crew',permissions:{complete:true}}),{status:403});
  await act('owner','save_workplace_permissions',{role:'crew',permissions:{complete:true}});
  assert.ok((await store.snapshot('crew')).tasks.some(t=>t.canComplete));
});
test('demo invitations rotate and revoke, remain owner-only, and cannot issue owner rank', async t => {
  const {store,act}=await setup(t);
  const first=await act('owner','create_demo_invite',{role:'hourly'});
  const second=await act('owner','create_demo_invite',{role:'hourly'});
  assert.notEqual(first.demoInvites[0].code,second.demoInvites[0].code);
  assert.equal(second.demoInvites.length,1);
  assert.equal(second.demoInvites[0].expiresAt,'2026-10-05T03:00:00.000Z');
  assert.equal((await store.snapshot('crew')).demoInvites,undefined);
  await assert.rejects(act('owner','create_demo_invite',{role:'owner'}),{status:400});
  const revoked=await act('owner','revoke_demo_invite',{role:'hourly'});
  assert.deepEqual(revoked.demoInvites,[]);
});
test('hours generate per-part weekday slots; date overrides, reset, revisions and assigned shifts are isolated', async t => {
  const {store,act}=await setup(t);
  let view=await act('owner','save_workplace_day',{weekday:1,bands:[{name:'오픈',start:'09:00',end:'13:00'},{name:'마감',start:'13:00',end:'22:00'}]});
  const templates=view.rosterTemplates.filter(t=>t.weekday===1);
  assert.equal(templates.length,6);
  const template=templates.find(t=>t.partId==='kitchen');
  const original=view.staffShifts;
  const change={date:'2026-09-28',partId:'kitchen',templateId:template.id,start:'10:00',end:'14:00'};
  view=await act('manager','save_roster_slot',change);
  assert.equal(view.rosterOverrides[0].start,'10:00');
  assert.deepEqual(view.staffShifts,original);
  assert.equal(view.rosterTemplates.find(t=>t.id===template.id).start,'09:00');
  await assert.rejects(act('crew','save_roster_slot',change),{status:403});
  await assert.rejects(act('owner','save_roster_slot',{...change,date:'2026-09-29'}),{status:409});
  await assert.rejects(act('owner','save_roster_slot',{...change,start:'09:15'}),{status:400});
  view=await act('owner','reset_roster_slot',change);
  assert.equal(view.rosterOverrides.length,0);
  await assert.rejects(store.mutate('owner',{...change,action:'save_roster_slot',revision:view.revision-1}),{status:409});
});
test('custom parts control assignment and task permissions independently from rank, including overnight overlap', async t => {
  const {store,act}=await setup(t);
  let view=await store.snapshot('owner');
  view=await act('owner','save_workplace_parts',{parts:[...view.workplace.parts,{name:'포장'}]});
  const partId=view.workplace.parts.at(-1).id;
  await act('owner','save_staff_profile',{tapperId:'tapper-crew',partIds:[partId],bands:[]});
  const shift={tapperId:'tapper-crew',partId,date:'2026-10-05',start:'22:00',end:'02:00'};
  view=await act('manager','save_staff_shift',shift);
  assert.equal(view.staffShifts.at(-1).partId,partId);
  await assert.rejects(act('manager','save_staff_shift',{...shift,date:'2026-10-06',start:'01:00',end:'03:00'}),{status:409});
  await assert.rejects(act('manager','save_staff_shift',{...shift,partId:'kitchen'}),{status:400});
  const id=view.staffShifts.at(-1).id;
  await assert.rejects(act('crew','delete_staff_shift',{id}),{status:403});
  view=await act('manager','delete_staff_shift',{id});
  assert.ok(!view.staffShifts.some(s=>s.id===id));
});
test('order board is opt-in, projected to crew, owner-only and never pretends a live connection', async t => {
  const {store,act}=await setup(t);
  const original=await store.snapshot('owner');
  assert.equal(original.orderBoardEnabled,false);
  await assert.rejects(act('manager','save_order_system',{enabled:true}),{status:403});
  await act('owner','save_order_system',{enabled:true});
  const crew=await store.snapshot('crew');
  assert.equal(crew.orderBoardEnabled,true);
  assert.equal(crew.store.profile.orderSystem.connectionStatus,'not_connected');
  const off=await act('owner','save_order_system',{enabled:false});
  assert.equal(off.orderBoardEnabled,false);
  assert.equal(off.tasks.length,original.tasks.length);
});
test('part task completion follows custom membership, not legacy role, and keeps pay private', async t => {
  const {store,act}=await setup(t);
  let view=await store.snapshot('owner');
  view=await act('owner','save_workplace_parts',{parts:[...view.workplace.parts,{name:'포장'}]});
  const partId=view.workplace.parts.at(-1).id;
  view=await act('owner','save_staff_profile',{tapperId:'tapper-crew',partIds:[partId],bands:[]});
  const template={id:'custom-part-check',title:'포장 확인',emoji:'📦',folderId:view.checklistFolders[0].id,slot:'준비',requiredRole:'cook',partId,zone:null,steps:[{id:'check',title:'수량 확인',manual:'수량을 확인해요.'}]};
  view=await act('owner','save_checklists',{folders:view.checklistFolders,templates:[...view.taskTemplates.filter(t=>!t.archivedAt),template]});
  const task=view.tasks.find(t=>t.templateId===template.id);
  assert.ok(task);
  const crew=await store.snapshot('crew');
  assert.equal(crew.tasks.find(t=>t.id===task.id).canComplete,true);
  assert.equal(crew.labor,undefined);
  assert.equal((await store.snapshot('cook')).tasks.find(t=>t.id===task.id).canComplete,false);
  await assert.rejects(act('cook','complete_step',{taskId:task.id,stepId:'check'}),{status:403});
  const done=await act('crew','complete_step',{taskId:task.id,stepId:'check'});
  assert.ok(done.tasks.find(t=>t.id===task.id).completedAt);
});
